version: '3.8'

services:
  semantic_search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: semantic_search
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    depends_on:
      - opensearch

  opensearch:
    image: public.ecr.aws/opensearchproject/opensearch:2
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: curl -s http://opensearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
    depends_on:
      - opensearch

volumes:
  opensearch_data:
