version: '3.8'

services:
  semantic_search_rails:
    build:
      context: .
      dockerfile: ./rails/Dockerfile
    container_name: semantic_search_rails
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/rails
    depends_on:
      - opensearch-dashboards

  semantic_search_sinatra:
    build:
      context: .
      dockerfile: ./sinatra/Dockerfile
    container_name: semantic_search_sinatra
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "4567:4567"
    volumes:
      - ./sinatra:/app
    depends_on:
      - opensearch-dashboards

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
    depends_on:
      - opensearch

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: curl -s http://opensearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

volumes:
  opensearch_data:
